<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="25893" started-at="2019-06-20T06:12:12Z" finished-at="2019-06-20T06:12:38Z">
    <groups>
    </groups>
    <test name="FirstTest" duration-ms="25893" started-at="2019-06-20T06:12:12Z" finished-at="2019-06-20T06:12:38Z">
      <class name="Testcase.TCTopupATM">
        <test-method status="PASS" signature="startBrowser()[pri:0, instance:Testcase.TCTopupATM@46d56d67]" name="startBrowser" is-config="true" duration-ms="10997" started-at="2019-06-20T06:12:12Z" finished-at="2019-06-20T06:12:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- startBrowser -->
        <test-method status="FAIL" signature="TopupFail_InputInvalidInfo3Times()[pri:0, instance:Testcase.TCTopupATM@46d56d67]" name="TopupFail_InputInvalidInfo3Times" duration-ms="14795" started-at="2019-06-20T06:12:23Z" finished-at="2019-06-20T06:12:38Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Đang xử lý] but found [Lỗi ngân hàng]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Đang xử lý] but found [Lỗi ngân hàng]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Testcase.TCTopupATM.TopupFail_InputInvalidInfo3Times(TCTopupATM.java:64)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TopupFail_InputInvalidInfo3Times -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:Testcase.TCTopupATM@46d56d67]" name="closeBrowser" is-config="true" duration-ms="81" started-at="2019-06-20T06:12:38Z" finished-at="2019-06-20T06:12:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Testcase.TCTopupATM -->
    </test> <!-- FirstTest -->
  </suite> <!-- Suite -->
</testng-results>
